#!/usr/bin/env python3
"""Create or find a GitLab MR for the AI workflow branch.

Reads config from environment variables set by the finalize stage.
Handles 409 (already exists) by searching for the existing MR by source branch,
trying both 'opened' and 'all' states, and matching on exact source_branch.
Falls back to creating a new MR with a [retry] suffix if no match found.

Writes the MR URL to /tmp/mr_url.txt on success.
"""
import json
import os
import subprocess
import sys
import urllib.parse


def main() -> int:
    branch = os.environ.get("BRANCH_NAME", "")
    target = os.environ.get("TARGET_BRANCH", "main")
    title = os.environ.get("MR_TITLE", "feat: AI-generated changes")
    description = os.environ.get("MR_DESCRIPTION", "Generated by Kiro CI.")
    token = os.environ.get("GL_TOKEN") or os.environ.get("GITLAB_TOKEN", "")
    host = os.environ.get("GITLAB_HOST", "gitlab.internal.ericsson.com")
    sandbox_repo = os.environ.get("SANDBOX_REPO_URL", "")

    if not token:
        print("ERROR: No GL_TOKEN or GITLAB_TOKEN available for MR creation")
        return 0

    if not sandbox_repo:
        print("ERROR: SANDBOX_REPO_URL not set")
        return 1

    # Encode project path from repo URL
    project_path = sandbox_repo.replace("https://", "").split("/", 1)[-1]
    if project_path.endswith(".git"):
        project_path = project_path[:-4]
    project = urllib.parse.quote(project_path, safe="")

    print(f"Project path (encoded): {project}")
    print(f"API URL: https://{host}/api/v4/projects/{project}/merge_requests")

    headers = [
        "--header", f"PRIVATE-TOKEN: {token}",
        "--header", "Content-Type: application/json",
    ]
    url = f"https://{host}/api/v4/projects/{project}/merge_requests"
    data = {
        "source_branch": branch,
        "target_branch": target,
        "title": title,
        "description": description,
    }

    # Attempt MR creation
    result = subprocess.run(
        ["curl", "-s", "-w", "\n%{http_code}", "--request", "POST"]
        + headers
        + ["--data", json.dumps(data), url],
        capture_output=True,
        text=True,
    )
    lines = result.stdout.strip().rsplit("\n", 1)
    body = lines[0] if len(lines) > 1 else result.stdout
    status = lines[1] if len(lines) > 1 else "unknown"
    print(f"HTTP {status}")

    try:
        resp = json.loads(body)
    except json.JSONDecodeError:
        print(f"Non-JSON response: {body[:500]}")
        return 0

    if "web_url" in resp:
        mr_url = resp["web_url"]
        print(f"MR created: {mr_url}")
        _write_url(mr_url)
        return 0

    if status == "409":
        # Search for existing MR by source branch — try opened first, then all states
        for state in ("opened", "all"):
            find_url = (
                f"https://{host}/api/v4/projects/{project}/merge_requests"
                f"?source_branch={urllib.parse.quote(branch, safe='')}&state={state}"
            )
            find_result = subprocess.run(
                ["curl", "-s"] + headers[:2] + [find_url],
                capture_output=True,
                text=True,
            )
            try:
                mrs = json.loads(find_result.stdout)
                if isinstance(mrs, list):
                    # Match on exact source_branch to avoid returning wrong MR
                    matching = [m for m in mrs if m.get("source_branch") == branch]
                    if matching:
                        mr_url = matching[0]["web_url"]
                        print(f"Existing MR ({state}): {mr_url}")
                        _write_url(mr_url)
                        return 0
            except json.JSONDecodeError:
                pass

        # No existing MR found despite 409 — retry with unique title
        print("No existing MR found for branch, retrying with unique title...")
        data["title"] = title + " [retry]"
        retry_result = subprocess.run(
            ["curl", "-s", "-w", "\n%{http_code}", "--request", "POST"]
            + headers
            + ["--data", json.dumps(data), url],
            capture_output=True,
            text=True,
        )
        retry_lines = retry_result.stdout.strip().rsplit("\n", 1)
        retry_body = retry_lines[0] if len(retry_lines) > 1 else retry_result.stdout
        try:
            retry_resp = json.loads(retry_body)
            if "web_url" in retry_resp:
                mr_url = retry_resp["web_url"]
                print(f"MR created (retry): {mr_url}")
                _write_url(mr_url)
                return 0
        except json.JSONDecodeError:
            pass
        print(f"MR retry failed: {retry_body[:300]}")
        return 0

    print(f"MR creation failed (HTTP {status}): {json.dumps(resp, indent=2)[:500]}")
    return 0


def _write_url(url: str) -> None:
    with open("/tmp/mr_url.txt", "w") as f:
        f.write(url)


if __name__ == "__main__":
    sys.exit(main())
