#!/bin/bash
# finalize_push.sh — Push sandbox changes to a feature branch in the sandbox repo.
#
# Expects:
#   - sandbox-artifact/ directory with kiro-cli's changes (no .git)
#   - sandbox/ directory freshly cloned with .git history
#   - Environment: JIRA_ISSUE_KEY, REPO_PATH, ISSUE_SUMMARY, WORKFLOW, CI_PIPELINE_URL
#
# Creates branch ai/{ISSUE_KEY}, overlays changes, commits, pushes.

set -euo pipefail

BRANCH_NAME="ai/${JIRA_ISSUE_KEY}"
echo "--- Preparing sandbox repo for push ---"

cd sandbox
git config user.email "kiro-ci@ericsson.com"
git config user.name "Kiro CI"
git checkout -b "$BRANCH_NAME"

# Overlay service code changes from artifact
if [ -d "../sandbox-artifact/${REPO_PATH}" ]; then
  cp -r "../sandbox-artifact/${REPO_PATH}/." "${REPO_PATH}/"
  echo "Overlaid ${REPO_PATH} from artifact"
fi

# Overlay aidlc-docs if present
if [ -d "../sandbox-artifact/aidlc-docs" ]; then
  mkdir -p aidlc-docs
  cp -r "../sandbox-artifact/aidlc-docs/." aidlc-docs/
  echo "Overlaid aidlc-docs from artifact"
fi

# Ensure sandbox repo has a .gitignore that excludes build artifacts
if [ ! -f ".gitignore" ] || ! grep -q "^target/$" .gitignore 2>/dev/null; then
  cat >> .gitignore << 'GITIGNORE'

# Build artifacts (added by Kiro CI)
target/
*.class
node_modules/
dist/
build/
__pycache__/
*.pyc
.coverage
coverage.xml
test-results.xml
GITIGNORE
  echo "Updated .gitignore to exclude build artifacts"
fi

# Clean up build artifacts that shouldn't be committed
rm -f "${REPO_PATH}/.coverage" "${REPO_PATH}/coverage.xml" \
      "${REPO_PATH}/test-results.xml" "${REPO_PATH}/pytest-output.txt"
find "${REPO_PATH}" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
# Remove entire target/ directory (Maven build output — never commit)
rm -rf "${REPO_PATH}/target"
# Remove Node.js build artifacts
rm -rf "${REPO_PATH}/node_modules" "${REPO_PATH}/dist" "${REPO_PATH}/build"

# Untrack any build artifacts that were previously committed to the repo
# (git rm --cached removes from index without deleting the file on disk)
git rm -r --cached "${REPO_PATH}/target" 2>/dev/null || true
git rm -r --cached "${REPO_PATH}/node_modules" 2>/dev/null || true
git rm -r --cached "${REPO_PATH}/dist" 2>/dev/null || true
git rm -r --cached "${REPO_PATH}/build" 2>/dev/null || true
find "${REPO_PATH}" -type d -name "__pycache__" | while read d; do
  git rm -r --cached "$d" 2>/dev/null || true
done

# Stage and commit
git add -A
if git diff --cached --quiet; then
  echo "No changes to commit — sandbox already up to date"
else
  git commit -m "feat(${JIRA_ISSUE_KEY}): ${ISSUE_SUMMARY}

Workflow: ${WORKFLOW}
Pipeline: ${CI_PIPELINE_URL}
Generated by Kiro CI"

  PUSH_TOKEN="${GL_TOKEN:-${GITLAB_TOKEN:-}}"
  if [ -z "$PUSH_TOKEN" ]; then
    echo "ERROR: No GL_TOKEN or GITLAB_TOKEN for push"
    exit 1
  fi

  SANDBOX_REPO_URL=$(python3 -c "import sys,json; print(json.load(sys.stdin).get('sandbox_repo',''))" < ../validate-output/project-config.json)
  PUSH_URL=$(echo "$SANDBOX_REPO_URL" | sed "s|https://|https://oauth2:${PUSH_TOKEN}@|")
  git push "$PUSH_URL" "$BRANCH_NAME" --force
  echo "Pushed branch $BRANCH_NAME"
fi

cd ..
